apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: apps-router
  namespace: openshift-ingress
spec:
  secretName: apps-router-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: apps.demo-east-v475-6c2gd.demo.red-chesterfield.com
  dnsNames:
  - apps.demo-east-v475-6c2gd.demo.red-chesterfield.com
  - "*.apps.demo-east-v475-6c2gd.demo.red-chesterfield.com"
  uriSANs:
  - spiffe://cluster.local/ns/sandbox/sa/example
  issuerRef:
    name: letsencrypt-staging
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer